### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by mistrysiddh** [MShawon/github-clone-count-badge#1]
I went through the whole documentation and also gave the permission which it been needed but still it gave me this error
```
Run git add .
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
![image](https://user-images.githubusercontent.com/25217451/145990202-9fc7ef4c-3b68-42b1-b627-1a66556ea22f.png)
![image](https://user-images.githubusercontent.com/25217451/145991847-b564fee3-53e7-45e3-9271-000590331170.png)

**Comment by andry81** [comment]
@mrfoxie You can take a look on a bit better implementation: https://github.com/andry81-devops/github-accum-stats

**Comment by MShawon** [comment]
That's odd.. I think you need atleast one clone ..see if that helps
